name: Build Assets

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build JavaScript/CSS for PRODUCTION
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          check-latest: true
      - name: Install NPM Dependencies
        run: npm install
      - name: Compile assets for production
        run: npm run production
