name: Build Assets

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build JavaScript/CSS for PRODUCTION
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: NPM Build
        run: |
          npm install
          npm run production
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: resources/dist/
